name: ECHO GITHUB_CONTEXT

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Echo GITHUB_CONTEXT
    runs-on: ubuntu-18.04

    steps:
      - name: Dump Gitbhub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GIT_SHA:      ${{ github.sha }}
          REPO_NAME:    ${{ github.repository }}
          REPO_BRANCH:  ${{ github.ref }}
        run: |
          #echo $GITHUB_CONTEXT
          echo $GIT_SHA
          echo $REPO_NAME
          echo $REPO_BRANCH
